workflows:
    sample-workflow:
        name: CatsAndModules
        max_build_duration: 120
        instance_type: mac_mini_m2
        
        environment:
            ios_signing:
                distribution_type: development
                bundle_identifier: ua.edu.ukma.apple-env.nozhenko.CatsAndModules-ArturNozhenko
                
            vars:
                BUNDLE_ID: "ua.edu.ukma.apple-env.nozhenko.CatsAndModules-ArturNozhenko"
                XCODE_SCHEME: "CatsAndModules_ArturNozhenko"
                
            groups:
                 - firebase_credentials
        
        
        scripts:
            - name: Set up code signing settings on Xcode project
              script: xcode-project use-profiles
              
              
            - name: Build ipa for distribution
              script: |
                xcode-project build-ipa \
                    --project "CatsAndModules_ArturNozhenko.xcodeproj" \
                    --scheme "$XCODE_SCHEME"

                
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        
        publishing:
            firebase:
    
                firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
    
                ios:
                    app_id: 1:904095942646:ios:c059ddeb528048758f69d7

        triggering:
            events:
                - push
            branch_patterns:
                - pattern: release_ArturNozhenko
                  include: true
                  source: true





